networks:
  bum_backend_net:
    driver: bridge
    name: bum_backend_net

services:
  postgres:
    image: postgres:17.4
    env_file: settings.conf
    environment:
      POSTGRES_DB: bumessenger
      POSTGRES_USER: postgres
    healthcheck:
      test: bash -c "pg_isready -U postgres -d bumessenger"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./settings.conf:/settings.conf
    networks:
      - bum_backend_net

  backend:
    build:
      context: .
      dockerfile: ./backend.dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file: settings.conf
    environment:
      DOCKER_CONNECTION_STRING: Host=postgres;Port=5432;Database=bumessenger;Username=postgres;Password=
    command: bash -c "export DOCKER_CONNECTION_STRING=$${DOCKER_CONNECTION_STRING}$${POSTGRES_PASSWORD};
                      ./BUMessenger.Web.Api"
    networks:
      - bum_backend_net

  pgadmin:
    image: dpage/pgadmin4:9.0
    depends_on:
      postgres:
        condition: service_healthy
    env_file: settings.conf
    environment:
      PGADMIN_LISTEN_PORT: 3000
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./settings.conf:/settings.conf
    networks:
      - bum_backend_net

  nginx:
    image: nginx:1.17.4
    depends_on:
      - pgadmin
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bum_backend_net
    ports:
      - 1234:80
