networks:
  bum_backend_net:
    driver: bridge
    name: bum_backend_net

services:
  postgres:
    image: postgres:17.4
    env_file: settings.conf
    volumes:
      - ./settings.conf:/settings.conf
    networks:
      - bum_backend_net

  pgadmin:
    image: dpage/pgadmin4:9.0
    depends_on:
      - postgres
    env_file: settings.conf
    environment:
      PGADMIN_LISTEN_PORT: 3000
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./settings.conf:/settings.conf
    networks:
      - bum_backend_net

  nginx:
    image: nginx:1.17.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bum_backend_net
    ports:
      - 80:80
