name: Building
on: push
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Building
        run: |
          docker compose up --exit-code-from backend
          if [[ 0 == $? ]]
          then
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          else
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          fi
